# document: https://github.com/realm/SwiftLint
# rules: https://realm.github.io/SwiftLint/rule-directory.html

included:
- ../andpad-camera

excluded:
- Pods
- ../andpad-camera/Classes/Common/Resources/Generated

disabled_rules:
- force_cast
- force_try
- function_parameter_count
- nesting
- self_in_property_initialization

opt_in_rules:
- anyobject_protocol
- array_init
- closure_end_indentation
- closure_spacing
- collection_alignment
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- convenience_type
- discarded_notification_center_observer
- discouraged_object_literal
- discouraged_optional_boolean
- empty_collection_literal
- empty_count
- empty_string
- empty_xctest_method
- explicit_init
- fallthrough
- file_name_no_space
- first_where
- flatmap_over_map_reduce
- identical_operands
- joined_default_parameter
- last_where
- let_var_whitespace
- literal_expression_end_indentation
- lower_acl_than_parent
- modifier_order
- multiline_arguments
- multiline_arguments_brackets
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- multiline_parameters_brackets
- operator_usage_whitespace
- optional_enum_case_matching
- overridden_super_call
- prefer_self_type_over_type_of_self
- prefer_zero_over_explicit_init
- private_action
- prohibited_super_call
- redundant_nil_coalescing
- redundant_type_annotation
- single_test_class
- sorted_first_last
- static_operator
- unavailable_function
- unneeded_parentheses_in_closure_argument
- untyped_error_in_catch
- vertical_parameter_alignment_on_call
- vertical_whitespace_closing_braces
- weak_delegate
- xct_specific_matcher
- yoda_condition

analyzer_rules:
- unused_import

custom_rules:
    # https://88-oct.atlassian.net/browse/PSK2-1424
    recommend_yyyy:
        name: "Recommend yyyy"
        regex: "Y{4}"
        match_kinds:
            - string
        message: "日付のフォーマットには原則yyyyを使用してください。YYYYは「暦週の基準年」を出力します。"
        severity: error

    # 致命的でない例外をCrashlyticsに報告してエラーの発生に気付けるようにする
    # unimplemented_record_error:
    #     name: "Unimplemented Crashlytics record(error:)"
    #     regex: "catch(?![^\\}]*record\\(error:)"
    #     message: "Please implement record(error:) method in catch block"
    #     severity: warning

cyclomatic_complexity:
    warning: 20
    error: 30

deployment_target:
    iOS_deployment_target: 14.0

file_length:
    warning: 1000
    error: 1500

function_body_length:
    warning: 100
    error: 200

identifier_name:
    allowed_symbols: "_"
    min_length: 1

large_tuple:
    warning: 3

line_length:
    warning: 200
    error: 300

trailing_whitespace:
    ignores_empty_lines: true

type_name:
    min_length: 0
    max_length: 1000
