name: Create a release pull request
jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # git-pr-release needs the git histories

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.4' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Create a release pull request
      env:
        GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PR_RELEASE_BRANCH_PRODUCTION: master
        GIT_PR_RELEASE_BRANCH_STAGING: develop
        GIT_PR_RELEASE_LABELS: release
        GIT_PR_RELEASE_TEMPLATE: .github/templates/create-release-pr.erb
        TZ: Asia/Tokyo
      run: |
        gem install -N git-pr-release -v "2.2.0"
        git-pr-release --no-fetch

on:
  workflow_dispatch:
  push:
    branches:
      - develop
