on:
  pull_request:
    branches: [master, feature/*]

jobs:
  danger:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - uses: nick-fields/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 3
          command: bundle exec danger
        timeout-minutes: 5
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
