# PR単位で差分があるファイルに対してSecretlint(シークレットスキャンツール)を実行し、
# アクセストークンなど秘匿すべき値をPRコメントで指摘するワークフローです
# 詳細は以下のドキュメントをご参照ください
# https://andpad-dev.esa.io/posts/8984

name: secretlint

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  secretlint:
    uses: 88labs/github-actions-reusable-workflows/.github/workflows/secretlint.yml@main
