name: Sync Code to Blueprint Repo

on:
  push:
    branches:
      - develop  # Thay đổi thành develop

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout `blueprint-camera-ios`
        uses: actions/checkout@v2
        with:
          repository: phaleandpad/blueprint-camera-ios
          ref: develop  # Lấy mã từ nhánh develop

      - name: Setup Git
        run: |
          git config --global user.name "phaleandpad"
          git config --global user.email "pha.le@andpad.co.jp"

      - name: Add remote with token
        run: |
          echo "Adding remote repository..."
          git remote add andpad https://$GH_TOKEN@github.com/phaleandpad/andpad-camera-ios.git
          git fetch andpad
          git merge andpad/develop --allow-unrelated-histories -m "Merge updates from andpad-camera-ios"

      - name: Push code to `blueprint-camera-ios`
        run: |
          echo "Pushing changes to blueprint-camera-ios..."
          git remote add blueprint https://$GH_TOKEN@github.com/phaleandpad/blueprint-camera-ios.git
          git push blueprint develop --force  # Push tới nhánh develop
